export interface CatalogueCategory { id: number; label: string; terms: readonly string[] }
// IDs are stable: append entries, never renumber. These are available topics,
// not empty bubbles; only categories receiving thoughts become visible.
const rows: [number, string, string][] = [
  [0, 'Other', ''],
  [1, 'Family', 'family|mom|mum|mother|dad|father|parents|parent|sister|brother|siblings|relatives|grandma|grandpa|grandparents|daughter|son'],
  [2, 'School', 'school|exam|exams|homework|college|university|class|classes|teacher|studying|assignment|assignments|education|grades|semester|lecture'],
  [3, 'Money', 'money|rent|bills|bill|debt|salary|budget|savings|financial|finances|bank|loan|loans|paycheck|afford|income|expenses|fee|fees|tuition|payment|payments|pay my bills|pay the bills'],
  [4, 'Work', 'work|job|boss|office|career|colleague|coworker|manager|shift|employment|interview|promotion|unemployed'],
  [5, 'Health', 'health|doctor|hospital|sick|illness|pain|headache|headaches|medication|medical|symptoms|surgery|appointment|therapy'],
  [6, 'Relationships', 'relationship|relationships|partner|boyfriend|girlfriend|husband|wife|dating|breakup|marriage|romance|couple'],
  [7, 'Friends', 'friend|friends|friendship|friendships|best friend|socialising|socializing'],
  [8, 'Home', 'house|home|moving house|apartment|landlord|roommate|cleaning|housing|chores|living space'],
  [9, 'The future', 'future|life plans|next chapter|long term|where my life is going|uncertain future'],
  [10, 'What if?', 'what if|worry|worried|worries|anxious|anxiety|overthinking|panic|nervous'],
  [11, 'Hobbies', 'hobby|hobbies|paint|painting|guitar|music|drawing|sketching|gardening|photography|crafts|knitting|free time'],
  [12, 'Sleep', 'sleep|sleeping|insomnia|waking up|awake at night|during the night|nightmare|nightmares|bedtime|cannot sleep|can t sleep'],
  [13, 'Travel', 'travel|trip|vacation|holiday|flight|airport|passport|tourism|visiting another country'],
  [14, 'Self-esteem', 'self esteem|confidence|self worth|not good enough|inadequate|insecure|self doubt|comparing myself'],
  [15, 'Feelings', 'feelings|emotions|sad|sadness|happy|angry|anger|frustrated|frustration|upset|overwhelmed|crying'],
  [16, 'Goals', 'goal|goals|ambition|ambitions|aspiration|aspirations|dreams|milestone|achievement|achieve'],
  [17, 'Habits', 'habit|habits|routine|routines|discipline|consistency|daily practice'],
  [18, 'Time', 'time management|running late|not enough time|busy schedule|calendar|schedule|scheduling'],
  [19, 'Responsibilities', 'responsibility|responsibilities|obligation|obligations|duties|duty|commitments|too much to do'],
  [20, 'Loneliness', 'lonely|loneliness|isolated|isolation|no one to talk to|all alone'],
  [21, 'Grief', 'grief|grieving|bereavement|passed away|loss of someone|mourning|died'],
  [22, 'Conflict', 'conflict|argument|arguments|arguing|fight|fighting|disagreement|tension|resentment'],
  [23, 'Gratitude', 'gratitude|grateful|thankful|appreciation|blessings'],
  [24, 'Celebrations', 'birthday|celebration|celebrate|anniversary|graduation|wedding|party'],
  [25, 'Identity', 'identity|who i am|sense of self|authentic|authenticity|sexual orientation|gender identity'],
  [26, 'Belonging', 'belonging|fit in|fitting in|excluded|accepted|acceptance|outsider'],
  [27, 'Body image', 'body image|appearance|how i look|weight|looks|mirror|body confidence'],
  [28, 'Food', 'food|eating|diet|nutrition|cooking|meals|appetite|hungry'],
  [29, 'Exercise', 'exercise|fitness|workout|gym|running|walking|sports|yoga|training'],
  [30, 'Social media', 'social media|instagram|tiktok|facebook|scrolling|online comparison|followers'],
  [31, 'Technology', 'technology|computer|phone|internet|app|software|screen time|digital|device'],
  [32, 'Community', 'community|neighbourhood|neighborhood|volunteering|volunteer|helping others|local group'],
  [33, 'Spirituality', 'spirituality|spiritual|faith|religion|prayer|praying|meditation|church'],
  [34, 'Safety', 'safe|safety|danger|unsafe|threat|threatened|abuse|harassment|emergency'],
  [35, 'Boundaries', 'boundaries|boundary|saying no|say no|people pleasing|personal space|privacy'],
  [36, 'Decisions', 'decision|decisions|choice|choices|choose|choosing|undecided|dilemma'],
  [37, 'Memories', 'memories|memory|nostalgia|nostalgic|childhood|remembering|the past'],
  [38, 'Parenting', 'parenting|childcare|child care|raising children|my baby|my toddler|motherhood|fatherhood'],
  [39, 'Caregiving', 'caregiving|caregiver|caring for|looking after|elderly|dependent|taking care of'],
  [40, 'Pets', 'pet|pets|dog|cat|puppy|kitten|animal companion'],
  [41, 'Nature', 'nature|outdoors|forest|ocean|beach|mountains|wildlife|environment|climate'],
  [42, 'Entertainment', 'entertainment|movie|movies|film|television|tv|gaming|games|concert|show'],
  [43, 'Creativity', 'creativity|creative|art|arts|artistic|writing|poetry|design|creating'],
  [44, 'Changes', 'change|changes|transition|transitions|starting over|new beginning|adjusting|life change'],
  [45, 'Burnout', 'burnout|burned out|burnt out|exhausted|exhaustion|drained|emotional fatigue'],
  [46, 'Productivity', 'productivity|productive|procrastination|procrastinating|focus|concentration|getting things done'],
  [47, 'Communication', 'communication|communicating|conversation|conversations|expressing myself|misunderstood|listening'],
  [48, 'Values', 'values|principles|ethics|integrity|morals|what matters to me'],
  [49, 'Meaning', 'meaning|purpose|life purpose|fulfilment|fulfillment|meaningless|why am i here'],
  [50, 'Learning', 'learn|learning|skill|skills|course|courses|language|languages|self improvement|personal growth'],
];
export const categoryCatalogue: readonly CatalogueCategory[] = rows.map(([id, label, terms]) => ({
  id, label, terms: terms ? terms.split('|') : [],
}));
export const categoryById = new Map(categoryCatalogue.map((category) => [category.id, category]));
